### ISSUE TITLE
Freeze on project opening

### ISSUE THREAD

**Issue by nisnevich** [shiraji/find-pull-request#105]
Reproduced every time I open IntelliJ community project. The freeze appears on call com.github.shiraji.findpullrequest.model.GitHistoryService.findLatestMergeCommit:
[thread dumps.zip](https://github.com/shiraji/find-pull-request/files/3718911/thread.dumps.zip)

> IntelliJ IDEA 2019.2.3 (Ultimate Edition)
Build #IU-192.6817.14, built on September 24, 2019
Licensed to JetBrains Team / Arseniy Nisnevich
Subscription is active until December 10, 2019
Runtime version: 11.0.4+10-b304.69 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15
GC: G1 Young Generation, G1 Old Generation
Memory: 4000M
Cores: 12
Registry: java.completion.argument.hints.internal=false, suppress.focus.stealing=false
Non-Bundled Plugins: com.github.kornilovaL.flamegraphProfiler, com.jetbrains.ChooseRuntime, Pythonid

```
"AWT-EventQueue-0 2019.2.3#IU-192.6817.14 IDEA, eap:false, os:Mac OS X 10.15, java-version:JetBrains s.r.o 11.0.4+10-b304.69 2019.2.3#IU-192.6817.14 IDEA, eap:false, os:Mac OS X 10.15, java-version:JetBrains s.r.o 11.0.4+10-b304.69" prio=0 tid=0x0 nid=0x0 waiting on condition
     java.lang.Thread.State: TIMED_WAITING
 on com.intellij.util.concurrency.Semaphore$Sync@1d7d385f
	at java.base@11.0.4/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@11.0.4/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
	at java.base@11.0.4/java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1079)
	at java.base@11.0.4/java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1369)
	at com.intellij.util.concurrency.Semaphore.waitForUnsafe(Semaphore.java:97)
	at com.intellij.util.concurrency.Semaphore.waitFor(Semaphore.java:87)
	at com.intellij.execution.process.ProcessHandler.waitFor(ProcessHandler.java:87)
	at com.intellij.execution.process.BaseOSProcessHandler.waitFor(BaseOSProcessHandler.java:221)
	at com.intellij.execution.process.OSProcessHandler.waitFor(OSProcessHandler.java:64)
	at git4idea.commands.GitTextHandler.waitForProcess(GitTextHandler.java:145)
	at git4idea.commands.GitHandler.runInCurrentThread(GitHandler.java:383)
	at git4idea.commands.GitImplBase.doRun(GitImplBase.java:172)
	at git4idea.commands.GitImplBase.run(GitImplBase.java:140)
	at git4idea.commands.GitImplBase.runCommandWithoutCollectingOutput(GitImplBase.java:78)
	at git4idea.commands.GitImpl.runCommandWithoutCollectingOutput(GitImpl.java:41)
	at git4idea.history.GitDetailsCollector.readRecordsFromHandler(GitDetailsCollector.kt:93)
	at git4idea.history.GitDetailsCollector.readFullDetailsFromHandler(GitDetailsCollector.kt:77)
	at git4idea.history.GitDetailsCollector.readFullDetails(GitDetailsCollector.kt:32)
	at git4idea.history.GitLogUtil.readFullDetails(GitLogUtil.java:210)
	at git4idea.history.GitHistoryUtils.history(GitHistoryUtils.java:143)
	at com.github.shiraji.findpullrequest.model.GitHistoryService.findLatestMergeCommit(GitHistoryService.kt:13)
	at com.github.shiraji.findpullrequest.activity.DetectHostingServiceStartupActivity.runActivity(DetectHostingServiceStartupActivity.kt:17)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivity(StartupManagerImpl.java:205)
	at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$null$1(StartupManagerImpl.java:181)
	at com.intellij.ide.startup.impl.StartupManagerImpl$$Lambda$1321/0x000000080116b040.run(Unknown Source)
	at com.intellij.openapi.project.DumbServiceImpl.doRun(DumbServiceImpl.java:389)
	at com.intellij.openapi.project.DumbServiceImpl.updateFinished(DumbServiceImpl.java:381)
	at com.intellij.openapi.project.DumbServiceImpl$$Lambda$2210/0x0000000801968440.run(Unknown Source)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:82)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$pollQueueLater$0(TransactionGuardImpl.java:67)
	at com.intellij.openapi.application.TransactionGuardImpl$$Lambda$735/0x00000008009ac440.run(Unknown Source)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:433)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:416)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.desktop@11.0.4/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop@11.0.4/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop@11.0.4/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop@11.0.4/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base@11.0.4/java.security.AccessController.doPrivileged(Native Method)
	at java.base@11.0.4/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop@11.0.4/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:824)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:773)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:412)
	at com.intellij.ide.IdeEventQueue$$Lambda$734/0x00000008009ac040.compute(Unknown Source)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:704)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:411)
	at java.desktop@11.0.4/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop@11.0.4/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop@11.0.4/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop@11.0.4/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop@11.0.4/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop@11.0.4/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by shiraji** [comment]
Let me check

**Comment by shiraji** [comment]
@nisnevich Please upgrade to v1.6.0. The version fix this problem and has much better performance.

I will close this issue but feel free to reopen if you find same error.

Thanks for reporting!
