### ISSUE TITLE
NoSuchElementException with IDEA 2019.1

### ISSUE THREAD

**Issue by ofry** [shiraji/find-pull-request#94]
```
IntelliJ IDEA 2019.1.1 (Ultimate Edition)
Build #IU-191.6707.61, built on April 16, 2019

JRE: 11.0.3+7-Ubuntu-1ubuntu1 amd64
JVM: OpenJDK 64-Bit Server VM by Ubuntu
Linux 5.0.0-14-generic
```

Find Pull Request v1.4.0

```
java.util.NoSuchElementException: List is empty.
	at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:194)
	at com.github.shiraji.findpullrequest.model.GitHistoryService.findLatestMergeCommit(GitHistoryService.kt:14)
	at com.github.shiraji.findpullrequest.activity.DetectHostingServiceStartupActivity.runActivity(DetectHostingServiceStartupActivity.kt:15)
	at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$logActivityDuration$2(StartupManagerImpl.java:152)
	at com.intellij.util.TimeoutUtil.measureExecutionTime(TimeoutUtil.java:74)
	at com.intellij.ide.startup.impl.StartupManagerImpl.logActivityDuration(StartupManagerImpl.java:152)
	at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$runPostStartupActivitiesFromExtensions$1(StartupManagerImpl.java:140)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivity(StartupManagerImpl.java:360)
	at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$queueSmartModeActivity$3(StartupManagerImpl.java:166)
	at com.intellij.openapi.project.DumbServiceImpl.doRun(DumbServiceImpl.java:380)
	at com.intellij.openapi.project.DumbServiceImpl.updateFinished(DumbServiceImpl.java:372)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$pollQueueLater$0(TransactionGuardImpl.java:74)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:741)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:690)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by shiraji** [comment]
Thanks for the reporting. I will fix this.

**Comment by shiraji** [comment]
Could you check v1.4.1?

**Comment by ofry** [comment]
Thank you, I think this bug fixed now.

**Comment by shiraji** [comment]
Thanks for the confirmation!
